// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: system_notify_template.proto

// system_notify_template 站内信模板表

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SystemNotifyTemplateService_SystemNotifyTemplateCreate_FullMethodName    = "/notify.SystemNotifyTemplateService/SystemNotifyTemplateCreate"
	SystemNotifyTemplateService_SystemNotifyTemplateUpdate_FullMethodName    = "/notify.SystemNotifyTemplateService/SystemNotifyTemplateUpdate"
	SystemNotifyTemplateService_SystemNotifyTemplateDelete_FullMethodName    = "/notify.SystemNotifyTemplateService/SystemNotifyTemplateDelete"
	SystemNotifyTemplateService_SystemNotifyTemplate_FullMethodName          = "/notify.SystemNotifyTemplateService/SystemNotifyTemplate"
	SystemNotifyTemplateService_SystemNotifyTemplateRecover_FullMethodName   = "/notify.SystemNotifyTemplateService/SystemNotifyTemplateRecover"
	SystemNotifyTemplateService_SystemNotifyTemplateList_FullMethodName      = "/notify.SystemNotifyTemplateService/SystemNotifyTemplateList"
	SystemNotifyTemplateService_SystemNotifyTemplateListTotal_FullMethodName = "/notify.SystemNotifyTemplateService/SystemNotifyTemplateListTotal"
)

// SystemNotifyTemplateServiceClient is the client API for SystemNotifyTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SystemNotifyTemplateService 服务
type SystemNotifyTemplateServiceClient interface {
	SystemNotifyTemplateCreate(ctx context.Context, in *SystemNotifyTemplateCreateRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateCreateResponse, error)
	SystemNotifyTemplateUpdate(ctx context.Context, in *SystemNotifyTemplateUpdateRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateUpdateResponse, error)
	SystemNotifyTemplateDelete(ctx context.Context, in *SystemNotifyTemplateDeleteRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateDeleteResponse, error)
	SystemNotifyTemplate(ctx context.Context, in *SystemNotifyTemplateRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateResponse, error)
	SystemNotifyTemplateRecover(ctx context.Context, in *SystemNotifyTemplateRecoverRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateRecoverResponse, error)
	SystemNotifyTemplateList(ctx context.Context, in *SystemNotifyTemplateListRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateListResponse, error)
	SystemNotifyTemplateListTotal(ctx context.Context, in *SystemNotifyTemplateListTotalRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateTotalResponse, error)
}

type systemNotifyTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemNotifyTemplateServiceClient(cc grpc.ClientConnInterface) SystemNotifyTemplateServiceClient {
	return &systemNotifyTemplateServiceClient{cc}
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplateCreate(ctx context.Context, in *SystemNotifyTemplateCreateRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateCreateResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplateCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplateUpdate(ctx context.Context, in *SystemNotifyTemplateUpdateRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateUpdateResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplateUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplateDelete(ctx context.Context, in *SystemNotifyTemplateDeleteRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateDeleteResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplateDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplate(ctx context.Context, in *SystemNotifyTemplateRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplateRecover(ctx context.Context, in *SystemNotifyTemplateRecoverRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateRecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateRecoverResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplateRecover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplateList(ctx context.Context, in *SystemNotifyTemplateListRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateListResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemNotifyTemplateServiceClient) SystemNotifyTemplateListTotal(ctx context.Context, in *SystemNotifyTemplateListTotalRequest, opts ...grpc.CallOption) (*SystemNotifyTemplateTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemNotifyTemplateTotalResponse)
	err := c.cc.Invoke(ctx, SystemNotifyTemplateService_SystemNotifyTemplateListTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemNotifyTemplateServiceServer is the server API for SystemNotifyTemplateService service.
// All implementations must embed UnimplementedSystemNotifyTemplateServiceServer
// for forward compatibility
//
// SystemNotifyTemplateService 服务
type SystemNotifyTemplateServiceServer interface {
	SystemNotifyTemplateCreate(context.Context, *SystemNotifyTemplateCreateRequest) (*SystemNotifyTemplateCreateResponse, error)
	SystemNotifyTemplateUpdate(context.Context, *SystemNotifyTemplateUpdateRequest) (*SystemNotifyTemplateUpdateResponse, error)
	SystemNotifyTemplateDelete(context.Context, *SystemNotifyTemplateDeleteRequest) (*SystemNotifyTemplateDeleteResponse, error)
	SystemNotifyTemplate(context.Context, *SystemNotifyTemplateRequest) (*SystemNotifyTemplateResponse, error)
	SystemNotifyTemplateRecover(context.Context, *SystemNotifyTemplateRecoverRequest) (*SystemNotifyTemplateRecoverResponse, error)
	SystemNotifyTemplateList(context.Context, *SystemNotifyTemplateListRequest) (*SystemNotifyTemplateListResponse, error)
	SystemNotifyTemplateListTotal(context.Context, *SystemNotifyTemplateListTotalRequest) (*SystemNotifyTemplateTotalResponse, error)
	mustEmbedUnimplementedSystemNotifyTemplateServiceServer()
}

// UnimplementedSystemNotifyTemplateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSystemNotifyTemplateServiceServer struct {
}

func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplateCreate(context.Context, *SystemNotifyTemplateCreateRequest) (*SystemNotifyTemplateCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplateCreate not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplateUpdate(context.Context, *SystemNotifyTemplateUpdateRequest) (*SystemNotifyTemplateUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplateUpdate not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplateDelete(context.Context, *SystemNotifyTemplateDeleteRequest) (*SystemNotifyTemplateDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplateDelete not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplate(context.Context, *SystemNotifyTemplateRequest) (*SystemNotifyTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplate not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplateRecover(context.Context, *SystemNotifyTemplateRecoverRequest) (*SystemNotifyTemplateRecoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplateRecover not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplateList(context.Context, *SystemNotifyTemplateListRequest) (*SystemNotifyTemplateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplateList not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) SystemNotifyTemplateListTotal(context.Context, *SystemNotifyTemplateListTotalRequest) (*SystemNotifyTemplateTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemNotifyTemplateListTotal not implemented")
}
func (UnimplementedSystemNotifyTemplateServiceServer) mustEmbedUnimplementedSystemNotifyTemplateServiceServer() {
}

// UnsafeSystemNotifyTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemNotifyTemplateServiceServer will
// result in compilation errors.
type UnsafeSystemNotifyTemplateServiceServer interface {
	mustEmbedUnimplementedSystemNotifyTemplateServiceServer()
}

func RegisterSystemNotifyTemplateServiceServer(s grpc.ServiceRegistrar, srv SystemNotifyTemplateServiceServer) {
	s.RegisterService(&SystemNotifyTemplateService_ServiceDesc, srv)
}

func _SystemNotifyTemplateService_SystemNotifyTemplateCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplateCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateCreate(ctx, req.(*SystemNotifyTemplateCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemNotifyTemplateService_SystemNotifyTemplateUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplateUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateUpdate(ctx, req.(*SystemNotifyTemplateUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemNotifyTemplateService_SystemNotifyTemplateDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplateDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateDelete(ctx, req.(*SystemNotifyTemplateDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemNotifyTemplateService_SystemNotifyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplate(ctx, req.(*SystemNotifyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemNotifyTemplateService_SystemNotifyTemplateRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplateRecover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateRecover(ctx, req.(*SystemNotifyTemplateRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemNotifyTemplateService_SystemNotifyTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateList(ctx, req.(*SystemNotifyTemplateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemNotifyTemplateService_SystemNotifyTemplateListTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemNotifyTemplateListTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateListTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemNotifyTemplateService_SystemNotifyTemplateListTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemNotifyTemplateServiceServer).SystemNotifyTemplateListTotal(ctx, req.(*SystemNotifyTemplateListTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemNotifyTemplateService_ServiceDesc is the grpc.ServiceDesc for SystemNotifyTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemNotifyTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.SystemNotifyTemplateService",
	HandlerType: (*SystemNotifyTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SystemNotifyTemplateCreate",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplateCreate_Handler,
		},
		{
			MethodName: "SystemNotifyTemplateUpdate",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplateUpdate_Handler,
		},
		{
			MethodName: "SystemNotifyTemplateDelete",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplateDelete_Handler,
		},
		{
			MethodName: "SystemNotifyTemplate",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplate_Handler,
		},
		{
			MethodName: "SystemNotifyTemplateRecover",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplateRecover_Handler,
		},
		{
			MethodName: "SystemNotifyTemplateList",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplateList_Handler,
		},
		{
			MethodName: "SystemNotifyTemplateListTotal",
			Handler:    _SystemNotifyTemplateService_SystemNotifyTemplateListTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system_notify_template.proto",
}
