version: "3"
services:
    mongodb:
        image: "mongo:latest"
        container_name: mongodb
        hostname: mongodb
        logging:
            driver: "none"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 654321
        ports:
            - "27017:27017"
        networks:
            abulo:
                ipv4_address: 172.18.1.2
        ulimits:
            nproc: 262144
            nofile: 262144
        restart: unless-stopped
        volumes:
            - ./docker/config/hosts:/etc/hosts
            - ./docker/data/mongodb/:/data/db
        command:  --auth
    mysql:
        image: "mysql:latest"
        container_name: mysql
        hostname: mysql
        logging:
            driver: "none"
        ports:
            - "3306:3306"
        networks:
            abulo:
                ipv4_address: 172.18.1.3
        ulimits:
            nproc: 262144
            nofile: 262144
        restart: unless-stopped
        volumes:
            - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/config/hosts:/etc/hosts
            - ./docker/data/mysql/:/var/lib/mysql
            - ./docker/data/mysql-files/:/var/lib/mysql-files
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        command: ["mysqld"]
    redis:
        image: "redis:latest"
        container_name: redis
        hostname: redis
        logging:
            driver: "none"
        ports:
            - "6379:6379"
        networks:
            abulo:
                ipv4_address: 172.18.1.4
        ulimits:
            nproc: 262144
            nofile: 262144
        restart: unless-stopped
        volumes:
            - ./docker/config/hosts:/etc/hosts
            - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./docker/data/redis/:/data
    jaeger:
        image: "jaegertracing/all-in-one:latest"
        container_name: jaeger
        hostname: jaeger
        logging:
            driver: "none"
        ports:
            - "16686:16686"
            # - "6831:6831/udp"
        networks:
            abulo:
                ipv4_address: 172.18.1.6
        ulimits:
            nproc: 262144
            nofile: 262144
        restart: unless-stopped
        volumes:
            - ./docker/config/hosts:/etc/hosts
    golang:
        image: "abulo/docker-golang:latest"
        container_name: golang
        hostname: golang
        logging:
            driver: "none"
        ports:
            - "10000:10000"
        networks:
            abulo:
                ipv4_address: 172.18.1.5
        ulimits:
            nproc: 262144
            nofile: 262144
        restart: unless-stopped
        user: root
        volumes:
            - ./docker/config/openresty/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./docker/config/openresty/nginx/vhost:/usr/local/openresty/nginx/conf/vhost
            - ./docker/config/hosts:/etc/hosts
            - ./apollo:/home/www/golang/src/apollo
            - ./run.sh:/home/www/golang/src/run.sh
        command: ["/home/www/golang/src/run.sh"]
    etcd:
        image: "bitnami/etcd:latest"
        container_name: etcd
        hostname: etcd
        logging:
            driver: "none"
        ports:
            - 2379:2379
            - 2380:2380
        networks:
            abulo:
                ipv4_address: 172.18.1.13
        ulimits:
            nproc: 262144
        mem_limit: 256m
        restart: unless-stopped
        volumes:
            - ./docker/config/hosts:/etc/hosts
            - ./docker/data/etcd:/opt/bitnami/etcd/data
        environment:
            - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
            - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
            - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
            - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
            - "ALLOW_NONE_AUTHENTICATION=yes"
            - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
            - "ETCD_NAME=node1"
            - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
networks:
    abulo:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
                  gateway: 172.18.1.1
