[db]
    [db.host1]
        Host = "172.18.1.3"
        Port = "3306"
        Username = "root"
        Password = "mysql"
        Charset = "utf8mb4"
        Database = "apollo"
        # MaxOpenConns 连接池最多同时打开的连接数
        MaxOpenConns = 64
        # MaxIdleConns 连接池里最大空闲连接数。必须要比maxOpenConns小
        MaxIdleConns = 64
        # MaxLifetime 连接池里面的连接最大存活时长(分钟)
        MaxLifetime = 5
        # MaxIdleTime 连接池里面的连接最大空闲时长(分钟)
        MaxIdleTime = 5
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
        DisableTrace = false
        # 数据库时区
        TimeZone = "PRC"
        # 驱动名称
        DriverName = "mysql"
        # 关闭预处理
        DisablePrepare = false
        # 是否解析时间
        ParseTime = true
        # clickhouse ip:port  clickhouse
        Addr = []
        # clickhouse 链接超时时间
        DialTimeout = "200ms"
        # clickhouse random/in_order (default random)
        OpenStrategy = "random"
        # clickhouse enable lz4 compression
        Compress = false
        # clickhouse 执行超时时间
        MaxExecutionTime = "200ms"
        # clickhouse 关闭 debug模式
        DisableDebug = false
[[proxydb]]
Name = "mysql"
Master = ["db.host1"]
Slave = ["db.host1"]