[mongodb]
    [mongodb.common]
        URI="mongodb://apollo:apollo@127.0.0.1:27017/apollo?authSource=admin&authMechanism=SCRAM-SHA-256"
        MaxConnIdleTime = 1
        MaxPoolSize = 64
        MinPoolSize = 10
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
        DisableTrace = false

[[proxymongodb]]
Name = "mongodb"
Node = ["mongodb.common"]
