[etcd]
    [etcd.common]
        Name="etcd"
        Endpoints = ["172.18.1.13:2379"]  # grpc注册到目标etcd中
        CertFile = ""
        KeyFile = ""
        CaCert = ""
        BasicAuth = false  # 是否开启认证
        UserName = ""
        Password = ""
        ConnectTimeout = "3s" # 连接超时时间
        Secure = false
        AutoSyncInterval = "0s" #自动同步member list的间隔
        Prefix = "Apollo" # 服务端注册到etcd的key前缀，配置客户端时候应该保持一致
        EnableTrace = true

[[proxyetcd]]
Name = "etcd"
Node = "etcd.common"