[server]
    [server.api]
        # 是否开启
        Disable = false
        # 监听 IP,如果是注册发现服务，需要填写内网 IP,如果是单机模式，则填写 127.0.0.1
        Host = "172.18.1.5"
        # 监听端口
        Port = 19999
        # 注册发现服务中的角色名称
        Deployment = "apollo-api"
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
        DisableTrace = false
        # 关闭慢日志查询
        DisableSlowQuery = true
        # 同监听一样
        ServiceAddress = "172.18.1.5:19999"
        # 慢日志
        SlowQueryThresholdInMill = 10000
    # [server.api]
    #     # 是否开启
    #     Disable = false
    #     # 监听 IP,如果是注册发现服务，需要填写内网 IP,如果是单机模式，则填写 127.0.0.1
    #     Host = "172.18.1.5"
    #     # 监听端口
    #     Port = 16666
    #     # 注册发现服务中的角色名称
    #     Deployment = "api"
    #     # 关闭指标采集
    #     DisableMetric = false
    #     # 关闭链路追踪
    #     DisableTrace = false
    #     # 同监听一样
    #     ServiceAddress = "172.18.1.5:16666"
    #     # 慢日志
    #     SlowQueryThresholdInMill = 10000
    [server.grpc]
        # 是否开启
        Disable = false
        # 监听 IP,如果是注册发现服务，需要填写内网 IP,如果是单机模式，则填写 127.0.0.1
        Host = "172.18.1.5"
        # 监听端口
        Port = 20000
        # 注册发现服务中的角色名称
        Deployment = "apollo-grpc"
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
        DisableTrace = false
        # 关闭慢日志查询
        DisableSlowQuery = false
        # 同监听一样
        ServiceAddress = "172.18.1.5:20000"
        # 慢日志
        SlowQueryThresholdInMill = 10000
    # [server.monitor]
    #     host = "172.18.1.5"
    #     port = 18889
    #     network = "tcp4"