# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "tenant" ]
  pull_request:
    branches: [ "tenant" ]

jobs:
  code: # 声明job的名字(这个job主要用来介绍，可以用做测试go test流程)
    runs-on: ubuntu-20.04   # 使用ubuntu系统镜像运行脚本
    # steps定义job的步骤，具体执行，运行xxx，-字符开头的一块则为一个步骤，可以配置多个步骤
    steps:
      - uses: actions/checkout@v4   # 步骤1：下载git仓库中的代码，使用官方提供，使用库用uses关键字
        with:
          clean: false

      - name: SetUp Go              # 步骤2：下载go代码
        uses: actions/setup-go@v5   # 使用官方提供
        with:
          go-version: 1.22.1          # 指定go版本1.22

      - name: Install linux deps
        run: |
            sudo apt-get -y install libvips-dev

      - name: Build Go              # 步骤3：编译仓库中的代码
        run: cloud/build.sh